# Generated by Django 2.0.1 on 2018-01-02 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorts', models.BooleanField(default=False)),
                ('jeans', models.BooleanField(default=False)),
                ('khakis', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('temp', models.IntegerField()),
                ('desc', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneakers', models.BooleanField(default=False)),
                ('boots', models.BooleanField(default=False)),
                ('flip_flops', models.BooleanField(default=False)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Checkin')),
            ],
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank', models.BooleanField(default=False)),
                ('t_shirt', models.BooleanField(default=False)),
                ('long_sleeve_shirt', models.BooleanField(default=False)),
                ('sweater', models.BooleanField(default=False)),
                ('jacket', models.BooleanField(default=False)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Checkin')),
            ],
        ),
        migrations.AddField(
            model_name='bottom',
            name='checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Checkin'),
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('user', 'date')},
        ),
    ]
