# Generated by Django 2.0.1 on 2018-01-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20180103_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='checkin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkin.Checkin'),
        ),
    ]
