# Generated by Django 2.0.1 on 2018-01-05 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkin', '0003_auto_20180103_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Boots',
            fields=[
                ('clothesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.ClothesBase')),
            ],
            bases=('clothes.clothesbase',),
        ),
        migrations.CreateModel(
            name='FlipFlops',
            fields=[
                ('clothesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.ClothesBase')),
            ],
            bases=('clothes.clothesbase',),
        ),
        migrations.CreateModel(
            name='Jeans',
            fields=[
                ('clothesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.ClothesBase')),
            ],
            bases=('clothes.clothesbase',),
        ),
        migrations.CreateModel(
            name='Khakis',
            fields=[
                ('clothesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.ClothesBase')),
            ],
            bases=('clothes.clothesbase',),
        ),
        migrations.CreateModel(
            name='LongSleeve',
            fields=[
                ('clothesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.ClothesBase')),
            ],
            bases=('clothes.clothesbase',),
        ),
        migrations.CreateModel(
            name='Shorts',
            fields=[
                ('clothesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.ClothesBase')),
            ],
            bases=('clothes.clothesbase',),
        ),
        migrations.CreateModel(
            name='Sneakers',
            fields=[
                ('clothesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.ClothesBase')),
            ],
            bases=('clothes.clothesbase',),
        ),
        migrations.CreateModel(
            name='Sweater',
            fields=[
                ('clothesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.ClothesBase')),
            ],
            bases=('clothes.clothesbase',),
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('clothesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.ClothesBase')),
            ],
            bases=('clothes.clothesbase',),
        ),
        migrations.CreateModel(
            name='TShirt',
            fields=[
                ('clothesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.ClothesBase')),
            ],
            bases=('clothes.clothesbase',),
        ),
        migrations.AddField(
            model_name='clothesbase',
            name='checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.Checkin'),
        ),
        migrations.AddField(
            model_name='clothesbase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
