# Generated by Django 2.0.1 on 2018-01-05 15:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_auto_20180103_1607'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clothesbase',
            unique_together={('user', 'checkin')},
        ),
    ]
